[package]
name = "todomvc_leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.0.17", default-features = false, features = ["csr", "stable"] }
uuid = { version = "1", features = ["v4", "js", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
